name: Destroy infra

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type EXACTLY: 'DESTROY'"
        required: true
        default: "no"

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    runs-on: ubuntu-latest

    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_ssh_pub_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform -chdir=infra init

      - name: terraform destroy with -auto-approve
        run: terraform -chdir=infra destroy -auto-approve -lock-timeout=5m
