name: Infra with Terraform + Ansible

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: setup terraform
      uses: hashicorp/setup-terraform@v3

    - name: terraform init
      run: terraform -chdir=infra init

    - name: terraform apply
      run: terraform -chdir=infra apply -auto-approve

    - name: get tf outputs
      run: terraform -chdir=infra output
